name: "AWS LB Blue/Green Status Action"
description: "This action determines if the an AWS LB is in a blue or green state"
inputs:
  blue_rule_arn:
    description: "The ARN of the blue rule"
    required: true
  green_rule_arn:
    description: "The ARN of the green rule"
    required: true
  switch_active_rule:
    description: "If true, the action will switch the active and inactive rules"
    required: false
    default: "false"
outputs:
  active_rule:
    description: "The name of the active rule"
  inactive_rule:
    description: "The name of the inactive rule"
  active_rule_arn:
    description: "The ARN of the active rule"
  inactive_rule_arn:
    description: "The ARN of the inactive rule"

runs:
  using: "node20"
  main: "dist/index.js"