name: "AWS LB Blue/Green Status Action"
description: "This action determines if the an AWS LB is in a blue or green state"
inputs:
  listener_arn:
    description: "The ARN of the listener"
    required: true
  blue_target_group_arn:
    description: "The ARN of the blue listener"
    required: true
  green_target_group_arn:
    description: "The ARN of the green listener"
    required: true
  blue_rule_name:
    description: "The name of the blue rule"
    required: false
    default: "blue"
  green_rule_name:
    description: "The name of the green rule"
    required: false
    default: "green"
  switch_target_group:
    description: "If true, the action will switch the active and inactive rules"
    required: false
    default: "false"
outputs:
  active_target_group: 
    description: "The ARN of the active target group"
  inactive_target_group:
    description: "The ARN of the inactive target group"
  active_target_group_arn:
    description: "The ARN of the active target group"
  inactive_target_group_arn:
    description: "The ARN of the inactive target group"

runs:
  using: "node20"
  main: "dist/index.js"